# Server configuration
server:
  port: ${PORT:5000}


spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true
      
# Mongo DB default port is 27017
  data.mongodb:
    host: localhost
    port: 0
    database: wt

# JWT
jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800
  tokenHead: "Bearer "
  route:
    authentication:
      path: auth
      refresh: refresh
      register: "auth/register"

# Logging configuration
logging:
  level:
    org.springframework:
      data: DEBUG
      security: DEBUG

#spring.boot.admin.url: http://localhost:8080
